### ISSUE TITLE
D6.4 ToC

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/testbeds#86]
# Introduction
# Technical Evaluation
*mention QoS evaluation was reportedto D3.3*
For each evaluation consider the following template:
 * Description of Component
 * Methodology and setup
 * Conformance metrics
 * Performance metrics
 * Conclusions and recommendations
*contributions should be provided in each repo hosting the source code component under docs/evaluation folder*
## Runtime (Paulo)
New performance tests for nodejs eg creation and updates of data objects
## Global Registry (TUB)
[Installation](https://github.com/reTHINK-project/dev-registry-global/blob/master/docs/install.md)
[Evaluation](https://github.com/reTHINK-project/dev-registry-global/blob/master/docs/evaluation.md)
## [Policy engines (IMT-TB)](https://github.com/reTHINK-project/specs/tree/master/tests/policy)
# Development Evaluations (Quobis)
*to update with TADHack results*
*ask internal developers to answer the survey and compare phase 1 with phase 2 answers*
## Results
# Trials Evaluations
 - specific tests for some topics addressed by reTHINK like interoperability
 - trials with real users
*mention IMS interoperability tests in Migration report*
## Interoperability evaluation
Reports to be provided [here](https://github.com/reTHINK-project/specs/tree/master/tests/interoperability)
### Smart Contextual Assistance and Contact Center (ALB/DT)
*WebRTC*
### Smart Contextual Assistance and Smart Enterprise App (ALB/APIZEE)
*Group Communication and User Status / User Availability*
*to be confirmed*
*no contributions to be included, see https://github.com/reTHINK-project/testbeds/issues/89#issuecomment-311921663*

### Smart Contextual Assistance and Participate (ALB/Quobis)
*Group Chat*
### Smart Contextual Assistance interworking with Slack (ALB)
*Group Chat interworking*
## Identity Management Evaluation
* Reports provided [here](https://github.com/reTHINK-project/specs/tree/master/tests/idm)*
## Identity Management and Discovery Services
*Reports to be provided [here](https://github.com/reTHINK-project/specs/tree/master/tests/discovery)*
## *Any other trial?*
# Architecture and Business Assessment (Orange)  
[D6.4 Architecture Assessment.docx](https://github.com/reTHINK-project/testbeds/files/1074728/D6.4.Architecture.Assessment.docx)
# Annexes with detailed tests results

**Comment by sbecot** [comment]
Added the chapter Architecture assessment in Word format (just copy paste it). Paulo, some of the lines are highlited in yellow, because I couldn't fill them. Could you have a look please?

[D6.4 Architecture Assessment.docx](https://github.com/reTHINK-project/testbeds/files/1074728/D6.4.Architecture.Assessment.docx)

**Comment by sdruesedow** [comment]
The working document for the Message Node assessment contribution with all currently available results is available as Word document here:
[D6.4 DTAG-MN-tests.docx](https://github.com/reTHINK-project/testbeds/blob/master/docs/d6.4/DTAG/D6.4%20DTAG-MN-tests.docx)

**Comment by sdruesedow** [comment]
The final contribution for the Message Node assessment tests is now available in [D6.4 DTAG-MN-tests.docx](https://github.com/reTHINK-project/testbeds/blob/master/docs/d6.4/DTAG/D6.4%20DTAG-MN-tests.docx). It contains a documentation of issues [Vertx#52](https://github.com/reTHINK-project/dev-msg-node-vertx/issues/52) and [NodeJS#30](https://github.com/reTHINK-project/dev-msg-node-nodejs/issues/30).

**Comment by tiagolb** [comment]
@pchainho Added Policy Engine evaluation by INESC-ID

**Comment by sdruesedow** [comment]
I just updated the MessageNode assessment tests secttion with the results of the latest (weekend) updates of @FredLuart on the NodeJS MN. All tests are passed now as expected. The NodeJS MN sections are updated accordingly.

The updated final contribution for the Message Node assessment tests is now available in [D6.4 DTAG-MN-tests.docx](https://github.com/reTHINK-project/testbeds/blob/master/docs/d6.4/DTAG/D6.4%20DTAG-MN-tests.docx). It contains a documentation of issue [Vertx#52](https://github.com/reTHINK-project/dev-msg-node-vertx/issues/52).
